# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('article_date', models.DateTimeField()),
                ('article_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Album')),
            ],
            options={
                'db_table': 'artice',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=200)),
                ('photo_place', models.ImageField(null=True, upload_to='images', verbose_name='photo')),
                ('photo_album', models.ManyToManyField(to='blog.Album')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
