# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_title_eng', models.CharField(max_length=200)),
                ('article_url', models.CharField(help_text='exemple - name_of_url', max_length=50)),
                ('article_text', models.TextField()),
                ('article_text_eng', models.TextField()),
                ('article_anatation', models.TextField(help_text='\u043a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435', null=True)),
                ('article_anatation_eng', models.TextField(help_text='short describtion', null=True)),
                ('article_date', models.DateTimeField()),
                ('article_picture', models.ImageField(null=True, upload_to='images', verbose_name='photo')),
                ('article_pictureSoc', models.ImageField(null=True, upload_to='images', verbose_name='photo for Soc')),
                ('article_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Album')),
            ],
            options={
                'db_table': 'artice',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_author', models.CharField(max_length=200)),
                ('article_author_eng', models.CharField(max_length=200)),
                ('article_authorUrl', models.CharField(help_text='exemple - name_of_url', max_length=200)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_user_first_name', models.CharField(max_length=50)),
                ('comment_user_last_name', models.CharField(max_length=50)),
                ('comment_user_link', models.CharField(max_length=150)),
                ('comment_user_picture', models.CharField(max_length=150)),
                ('comment_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_title', models.CharField(max_length=200)),
                ('country_title_eng', models.CharField(max_length=200)),
                ('country_url', models.CharField(help_text='name for URL. exemple - name_of_url', max_length=50)),
                ('country_picture', models.ImageField(null=True, upload_to='images', verbose_name='photo')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_date', models.CharField(max_length=50)),
                ('map_text', models.CharField(max_length=200)),
                ('map_text_eng', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'map',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=200)),
                ('mark_name_eng', models.CharField(max_length=200)),
                ('mark_url', models.CharField(help_text='exemple - name_of_url', max_length=50)),
                ('mark_article', models.ManyToManyField(to='blog.Article')),
            ],
            options={
                'db_table': 'mark',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_title', models.CharField(max_length=50)),
                ('marker_latitude', models.CharField(help_text='\u0448\u0438\u0440\u043e\u0442\u0430', max_length=50)),
                ('marker_longitude', models.CharField(help_text='\u0434\u043e\u043b\u0433\u043e\u0442\u0430', max_length=50)),
            ],
            options={
                'db_table': 'marker',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_place', models.ImageField(null=True, upload_to='images', verbose_name='photo')),
                ('photo_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Album')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_url', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430 \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u043c', max_length=50)),
                ('video_iframe', models.CharField(help_text='\u0441 \u044e\u0442\u0443\u0431\u0430 src___', max_length=200)),
                ('video_text', models.TextField()),
                ('video_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Country')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Country'),
        ),
    ]
