# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_url', models.CharField(max_length=50)),
                ('article_text', models.TextField()),
                ('article_date', models.DateTimeField()),
                ('article_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Album')),
            ],
            options={
                'db_table': 'artice',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_title', models.CharField(max_length=200)),
                ('country_url', models.CharField(max_length=50)),
                ('country_picture', models.ImageField(null=True, upload_to='images', verbose_name='photo')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=200)),
                ('mark_url', models.CharField(max_length=50)),
                ('mark_article', models.ManyToManyField(to='blog.Article')),
            ],
            options={
                'db_table': 'mark',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_place', models.ImageField(null=True, upload_to='images', verbose_name='photo')),
                ('photo_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Album')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Country'),
        ),
    ]
