# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
