# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_pictureSoc',
        ),
    ]
