# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_article_picturesoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_pictureSoc',
            field=models.ImageField(null=True, upload_to='images', verbose_name='photo for Soc'),
        ),
    ]
