# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161219_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_url', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430 \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u043c', max_length=50)),
                ('video_src', models.CharField(help_text='\u0441 \u044e\u0442\u0443\u0431\u0430 src___', max_length=200)),
                ('video_text', models.TextField()),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='country_url',
            field=models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430 \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u043c', max_length=50),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_url',
            field=models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430 \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u043c', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='video_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Country'),
        ),
    ]
