# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161222_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_title', models.CharField(max_length=50)),
                ('marker_latitude', models.CharField(max_length=50)),
                ('marker_longitude', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marker',
            },
        ),
    ]
