# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mark_mark_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Country'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_album',
            field=models.ManyToManyField(null=True, to='blog.Album'),
        ),
    ]
