# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161212_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_picture',
            field=models.ImageField(null=True, upload_to='images', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_album',
            field=models.ManyToManyField(to='blog.Album'),
        ),
    ]
