# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170208_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_picture',
            field=models.ImageField(null=True, upload_to='images', verbose_name='photo'),
        ),
    ]
