# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_authorUrl',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
