# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170212_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_author', models.CharField(max_length=200)),
                ('article_authorUrl', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_authorUrl',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
