# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170212_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_user_first_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user_last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user_link',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user_picture',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
