# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170218_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_anatation_eng',
            field=models.TextField(help_text='short describtion', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text_eng',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_title_eng',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='article_author_eng',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_title_eng',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_name_eng',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.CharField(help_text='exemple - name_of_url', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='article_authorUrl',
            field=models.CharField(help_text='exemple - name_of_url', max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_url',
            field=models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f URL. exemple - name_of_url', max_length=50),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_url',
            field=models.CharField(help_text='exemple - name_of_url', max_length=50),
        ),
    ]
