# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='information',
        ),
    ]
