# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170331_1658'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitorinformation',
            table=None,
        ),
    ]
